env: standard
runtime: nodejs16
service: default

handlers:
    - url: /.*
      secure: always
      script: auto

automatic_scaling:
    min_idle_instances: 1
    max_idle_instances: 1
    min_pending_latency: automatic
    max_pending_latency: automatic
    min_instances: 1
    max_instances: 1
